### ISSUE TITLE
Lowecase transform breaks character search

### ISSUE THREAD

**Issue by Deznait** [Eblancho/NodeRIO#1]
Hi,

I'm using this library for a Discord Bot, and I'm having an issue with characters with special charects on their names.

For example, the character "Ðæ", when used the toLowerCase() function on the name, converts it to "ðæ", wich the API from RaiderIO does not found:
OK - https://raider.io/api/v1/characters/profile?region=eu&realm=zul-jin&name=Ðæ
KO - https://raider.io/api/v1/characters/profile?region=eu&realm=zul-jin&name=ðæ

If you chenge the line 116 of "src\Character\index.js", from
`+ '&name=${name.toLowerCase()}'`
to
`+ '&name=${name}'`
the issue is fixed.

**Comment by Eblancho** [comment]
Hello,

Thank you for bringing this problem to my attention.

I have corrected it and deployed version 1.0.10 on NPM.

Please let me know if the problem is solved!

P.S : I haven't updated this library with the S2 changes yet, I'll take care of it soon :)

**Comment by Deznait** [comment]
Thanks a lot, it solved the issue!
